// This file was generated by graphql-codegen. DO NOTT EDIT MANUALLY.
// biome-ignore lint: This file was generated by graphql-codegen.
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';
import type { Account } from '../../account/model/index.js';
import type { Organization } from '../../organization/model/index.js';
import type { GraphQLContext } from '../../../server/apollo/context.js';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export type RequireFields<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  UUID: { input: string; output: string; }
};

export type GqlAccount = {
  __typename?: 'Account';
  id: Scalars['UUID']['output'];
  name: Scalars['String']['output'];
  organizations: Array<GqlOrganization>;
};

export type GqlMutation = {
  __typename?: 'Mutation';
  signUp?: Maybe<GqlSignUpPayload>;
};


export type GqlMutationSignUpArgs = {
  input: GqlSignUpInput;
};

export type GqlOrganization = {
  __typename?: 'Organization';
  accounts: Array<GqlAccount>;
  id: Scalars['UUID']['output'];
  name: Scalars['String']['output'];
};

export type GqlQuery = {
  __typename?: 'Query';
  account?: Maybe<GqlAccount>;
  organization?: Maybe<GqlOrganization>;
};


export type GqlQueryAccountArgs = {
  id: Scalars['UUID']['input'];
};


export type GqlQueryOrganizationArgs = {
  id: Scalars['UUID']['input'];
};

export type GqlSignUpInput = {
  name: Scalars['String']['input'];
};

export type GqlSignUpPayload = {
  __typename?: 'SignUpPayload';
  account: GqlAccount;
};

export type WithIndex<TObject> = TObject & Record<string, any>;
export type ResolversObject<TObject> = WithIndex<TObject>;

export type ResolverTypeWrapper<T> = Promise<T> | T;


export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> = ResolverFn<TResult, TParent, TContext, TArgs> | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = {}, TContext = {}> = (obj: T, context: TContext, info: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>;



/** Mapping between all available schema types and the resolvers types */
export type GqlResolversTypes = ResolversObject<{
  Account: ResolverTypeWrapper<Account>;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
  Mutation: ResolverTypeWrapper<{}>;
  Organization: ResolverTypeWrapper<Organization>;
  Query: ResolverTypeWrapper<{}>;
  SignUpInput: GqlSignUpInput;
  SignUpPayload: ResolverTypeWrapper<Omit<GqlSignUpPayload, 'account'> & { account: GqlResolversTypes['Account'] }>;
  String: ResolverTypeWrapper<Scalars['String']['output']>;
  UUID: ResolverTypeWrapper<Scalars['UUID']['output']>;
}>;

/** Mapping between all available schema types and the resolvers parents */
export type GqlResolversParentTypes = ResolversObject<{
  Account: Account;
  Boolean: Scalars['Boolean']['output'];
  Mutation: {};
  Organization: Organization;
  Query: {};
  SignUpInput: GqlSignUpInput;
  SignUpPayload: Omit<GqlSignUpPayload, 'account'> & { account: GqlResolversParentTypes['Account'] };
  String: Scalars['String']['output'];
  UUID: Scalars['UUID']['output'];
}>;

export type GqlAccountResolvers<ContextType = GraphQLContext, ParentType extends GqlResolversParentTypes['Account'] = GqlResolversParentTypes['Account']> = ResolversObject<{
  id?: Resolver<GqlResolversTypes['UUID'], ParentType, ContextType>;
  name?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  organizations?: Resolver<Array<GqlResolversTypes['Organization']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlMutationResolvers<ContextType = GraphQLContext, ParentType extends GqlResolversParentTypes['Mutation'] = GqlResolversParentTypes['Mutation']> = ResolversObject<{
  signUp?: Resolver<Maybe<GqlResolversTypes['SignUpPayload']>, ParentType, ContextType, RequireFields<GqlMutationSignUpArgs, 'input'>>;
}>;

export type GqlOrganizationResolvers<ContextType = GraphQLContext, ParentType extends GqlResolversParentTypes['Organization'] = GqlResolversParentTypes['Organization']> = ResolversObject<{
  accounts?: Resolver<Array<GqlResolversTypes['Account']>, ParentType, ContextType>;
  id?: Resolver<GqlResolversTypes['UUID'], ParentType, ContextType>;
  name?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export type GqlQueryResolvers<ContextType = GraphQLContext, ParentType extends GqlResolversParentTypes['Query'] = GqlResolversParentTypes['Query']> = ResolversObject<{
  account?: Resolver<Maybe<GqlResolversTypes['Account']>, ParentType, ContextType, RequireFields<GqlQueryAccountArgs, 'id'>>;
  organization?: Resolver<Maybe<GqlResolversTypes['Organization']>, ParentType, ContextType, RequireFields<GqlQueryOrganizationArgs, 'id'>>;
}>;

export type GqlSignUpPayloadResolvers<ContextType = GraphQLContext, ParentType extends GqlResolversParentTypes['SignUpPayload'] = GqlResolversParentTypes['SignUpPayload']> = ResolversObject<{
  account?: Resolver<GqlResolversTypes['Account'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}>;

export interface GqlUuidScalarConfig extends GraphQLScalarTypeConfig<GqlResolversTypes['UUID'], any> {
  name: 'UUID';
}

export type GqlResolvers<ContextType = GraphQLContext> = ResolversObject<{
  Account?: GqlAccountResolvers<ContextType>;
  Mutation?: GqlMutationResolvers<ContextType>;
  Organization?: GqlOrganizationResolvers<ContextType>;
  Query?: GqlQueryResolvers<ContextType>;
  SignUpPayload?: GqlSignUpPayloadResolvers<ContextType>;
  UUID?: GraphQLScalarType;
}>;


export type GqlUuid = Scalars["UUID"];