import type { CodegenConfig } from "@graphql-codegen/cli"

const basePlugins = [
  {
    add: {
      content: [
        "// biome-ignore lint: This file was generated by graphql-codegen.",
      ],
    },
  },
]

const config: CodegenConfig = {
  schema: "./src/module/**/schema.graphql",
  overwrite: true,
  emitLegacyCommonJSImports: false,
  generates: {
    "./src/module/": {
      preset: "graphql-modules",
      presetConfig: {
        useGraphQLModules: false,
        baseTypesPath: "./common/types/graphql.ts",
        importBaseTypesFrom: "../../common/types/graphql.ts",
        filename: "types/graphql.ts",
        requireRootResolvers: true,
      },
      config: {
        useTypeImports: true,
        namingConvention: {
          transformUnderscore: true,
        },
        typesPrefix: "Gql",
        enumsAsTypes: true,
        contextType: "../../../server/apollo/context.js#GraphQLContext",
        useIndexSignature: true,
        mappers: {
          Account: "../../account/model/index.js#Account",
          Organization: "../../organization/model/index.js#Organization",
        },
      },
      plugins: ["typescript", "typescript-resolvers", ...basePlugins],
    },
  },
}

export default config
