import type { CodegenConfig } from "@graphql-codegen/cli"

const config: CodegenConfig = {
  schema: "./src/module/**/schema.graphql",
  overwrite: true,
  emitLegacyCommonJSImports: false,
  generates: {
    "./src/module/common/types/graphql.ts": {
      config: {
        useTypeImports: true,
        namingConvention: {
          transformUnderscore: true,
        },
        enumsAsTypes: true,
        contextType: "../../../server/apollo/context.js#GraphQLContext",
        useIndexSignature: true,
        typesPrefix: "Gql",
        mappers: {
          Account: "../../account/model/index.js#Account",
          Organization: "../../organization/model/index.js#Organization",
        },
      },
      plugins: [
        "typescript",
        "typescript-resolvers",
        {
          add: {
            // NOTE: contentの内容を変数化して共通利用しようとすると、なぜかcodegenが全てのファイルの内容を削除してしまうので、重複して記述する
            content: [
              "// This file was generated by graphql-codegen. DO NOTT EDIT MANUALLY.",
              "// biome-ignore lint: This file was generated by graphql-codegen.",
            ],
          },
        },
      ],
    },
    "./src/module/": {
      preset: "graphql-modules",
      presetConfig: {
        useGraphQLModules: false,
        baseTypesPath: "./common/types/graphql.ts",
        importBaseTypesFrom: "../../common/types/graphql.ts",
        filename: "types/graphql.ts",
        requireRootResolvers: true,
      },
      config: {
        useTypeImports: true,
        namingConvention: {
          transformUnderscore: true,
        },
        typesPrefix: "Gql",
        enumsAsTypes: true,
      },
      plugins: [
        {
          add: {
            // NOTE: contentの内容を変数化して共通利用しようとすると、なぜかcodegenが全てのファイルの内容を削除してしまうので、重複して記述する
            content: [
              "// This file was generated by graphql-codegen. DO NOTT EDIT MANUALLY.",
              "// biome-ignore lint: This file was generated by graphql-codegen.",
            ],
          },
        },
      ],
    },
  },
}

export default config
