// This file was generated by graphql-codegen. DO NOTT EDIT MANUALLY.
// biome-ignore lint: This file was generated by graphql-codegen.
import type * as Types from "../../common/types/graphql.ts";
export namespace AccountModule {
  interface DefinedFields {
    Query: 'account';
    Mutation: 'signUp';
    Account: 'id' | 'name' | 'organizations';
    SignUpPayload: 'account';
  };
  
  interface DefinedInputFields {
    SignUpInput: 'name';
  };
  
  export type Query = Pick<Types.GqlQuery, DefinedFields['Query']>;
  export type Account = Pick<Types.GqlAccount, DefinedFields['Account']>;
  export type UUID = Types.GqlUuid;
  export type Mutation = Pick<Types.GqlMutation, DefinedFields['Mutation']>;
  export type SignUpPayload = Pick<Types.GqlSignUpPayload, DefinedFields['SignUpPayload']>;
  export type SignUpInput = Pick<Types.GqlSignUpInput, DefinedInputFields['SignUpInput']>;
  export type Organization = Types.GqlOrganization;
  
  export type QueryResolvers = Required<Pick<Types.GqlQueryResolvers, DefinedFields['Query']>>;
  export type MutationResolvers = Required<Pick<Types.GqlMutationResolvers, DefinedFields['Mutation']>>;
  export type AccountResolvers = Pick<Types.GqlAccountResolvers, DefinedFields['Account'] | '__isTypeOf'>;
  export type SignUpPayloadResolvers = Pick<Types.GqlSignUpPayloadResolvers, DefinedFields['SignUpPayload'] | '__isTypeOf'>;
  
  export interface Resolvers {
    Query: QueryResolvers;
    Mutation: MutationResolvers;
    Account?: AccountResolvers;
    SignUpPayload?: SignUpPayloadResolvers;
  };
}