name: tbls
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - db/schema.sql
      - db/tbls.yml

jobs:
  tbls:
    name: generate-erd-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Execute migration
        run: |
          go install github.com/sqldef/sqldef/cmd/psqldef@latest
          psqldef -h postgres -p 5432 -U postgres app < /db/schema.sql
      - uses: k1low/setup-tbls@v1
      - name: Run tbls
        run: |
          tbls doc -c ./db/tbls.yml --rm-dist
      - name: Check diff
        id: check-diff
        run: |
          git add .
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit ER diagram
        if: steps.check-diff.outputs.changes != '0'
        uses: EndBug/add-and-commit@v9
        id: commit
        with:
          message: "Update ER diagram"
          default_author: github_actions
      - name: PR Comment
        if: steps.check-diff.outputs.changes != '0' && steps.commit.outcome == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `✨ ER diagram が更新されました。 commit: ${context.sha}.`
            })
